@startuml ctd_qc
'skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
box "Välj filer, Knappar" #LightBlue
participant Filer
participant StartQC

end box
box "Visa val: Visa" #GreenYellow
participant GUI1
end box
box "Auto QC-Steg" #LightGreen
participant QC1
participant QC2
participant QC3
end box

box "Visuellgranskning" #GreenYellow
participant GUI2
participant Bokeh
participant Plot
end box

database "Data Scifi01"
database "Data raw"
database "Data local"

== Välj filer ==
User -> Filer: Välj fil/filer NSF

    alt Default dir
        "Data Scifi01" -> GUI1: Visa default dir ÅR
    else Scifi01 nere
        "Data local" -> GUI1: Visa local dir ÅR
    end

Filer -> GUI1: Visa valda filer.
User -> GUI1: Ta bort oönskade Filer

== Välj QC-steg ==
User -> QC1: Klicka i valda QC-steg.
User -> StartQC: Tryck Start auto QC
StartQC -> QC1: Kör valda QC rutiner
QC1 -> QC3: 

== QC-VIS kontroll ==
QC3 -> GUI2: QC rapport
QC3 -> Bokeh: Resultat 
User -> Bokeh: Visuell kontroll, justera flaggor, godkänn
Bokeh -> "Data Scifi01": Uppdatera NSF
Bokeh -> "Data local": Uppdatera NSF

User -> Plot: Välj plotning
Plot -> "Data Scifi01": Skapa plottar på servern
Plot -> "Data local": Skapa plottar lokalt, skriv ut?

== Data management == 
box "Data manageement" #LightBlue
participant GUI3
participant FTP
participant LIMS
participant SVN
participant DV
end box

User->Filer: Välj justera valda filer
Filer -> GUI3: Valda filer
User -> FTP: Skickar filer till FTP
User -> LIMS: Skickar filer till LIMS
User -> SVN: Skickar filer till SVN (eller GIT)
User -> DV: Skapa leveransmall till DV
DV -> "Data local": Leveransmall på alla valda filer skapas lokalt. 

@enduml