@startuml ctd_processing
'skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
box "Välj CTD, Filer, XMLCON Knappar" #LightBlue
participant CTDs
participant Filer
participant XMLCON
participant Start
end box
box "Visa val: Visa" #GreenYellow
participant GUI1
end box
box "Processeringssteg SBE" #LightGreen
participant DatCNV
participant Filter
participant Align
participant CellTM
participant LoopEdit
participant Derive
participant BinAvg
participant Split
participant BottleSum
participant SeaPlot
end box

box "Processeringssteg: Visa" #GreenYellow
participant GUI2
end box

box "Processeringssteg extra" #LightGreen
participant TrueDepth
participant SoundVel
participant Header_fix
participant SensorInfo
end box


collections Config

database "Data Scifi01"
database "Data raw"
database "Data local"

== Välj CTD, processingssteg ==
User -> CTDs: Välj CTD
CTDs -> GUI1: Visa vald CTD
    alt Om SBE19 eller MVP200 är vald
        CTDs -> Config: Hämta XMLCON
        Config -> GUI1: Hämta XMLCON
    else Övriga data har egen XMLCON
        "Data local" -> GUI1: XMLCON finns tillsammans med data
    end

CTDs -> Config: Visa default processering för vald CTD
Config -> GUI2: Visa vilket steg som körs, samt söktväg


== Välj filer att processera ==
CTDs -> "Data local": Hämtar raw filer för processering i ctd-temp
"Data local" -> GUI1: Visa tillgängliga filer. Andra raw-filer som man vill processera läggs i ctd-temp.

User -> Filer: Välj fil/filer att processera
Filer -> GUI1: Visa valda filer.
User -> GUI1: Ta bort oönskade Filer

== Justera processering ==
User -> DatCNV: Gör ev justeringar i processing.

    alt Välj Soak
        LoopEdit -> Config: Default. 7-8m
        Config -> GUI2: Hämta o kör LoopEdit.psa
    else
        LoopEdit -> Config: Deep. 15m
        Config -> GUI2: Hämta o kör LoopEdit_deep.psa
    else 
        LoopEdit -> Config: Shallow. 5m
        Config -> GUI2: Hämta o kör LoopEdit_shallow.psa
    end

    alt Välj om Tau-korrektion O2 av/på
        Derive -> Config: Tau på (default)
        Config -> GUI2: Justera derive.psa
    else
        Derive -> Config: Tau av
        Config -> GUI2: Justera derive.psa
    end

== Visa sökvägar till data, raw, processed == 
"Data raw" -> GUI1: Raw-Data: \\\scifi01\\scifi\\Data\\mcseabirdchem\\data\\
"Data Scifi01" -> GUI1: NSF-Data: \\\scifi01\\scifi\\Processed\\mcseabirdchem\\data\\ 
"Data local" -> GUI1: Locl-data: (Raw/cnv/NSF) C:\ctd\data\

== Kör Processering, skapa CNV, Raw, SBE-plottar och SensorInfo ==
User -> Start: Klicka start
Start -> DatCNV: Kör processering
DatCNV -> SeaPlot: 
SeaPlot -> TrueDepth: Kör extra processeringssteg
TrueDepth -> Header_fix:
Header_fix -> Config: Skapa SensorInfo från XMLCON (SBE19/MVP200) 
Header_fix -> "Data local": Skapa SensorInfo från XMLCON-fil (SBE09) i temp 
"Data local" -> SensorInfo:  
Config -> SensorInfo: och instrument.xlsx
SensorInfo -> "Data local": Spara sensorinfo med samma filnamn.sensorinfo
SensorInfo -> "Data local": Skapa CNV, Raw o ev SBE-plottar. 
SensorInfo -> "Data raw": Kopiera Raw-filer till servern


== CNV + SensorInfo till NSF ==
"Data local" -> "Data local": Skapa NSF lokalt
"Data local" -> "Data Scifi01": Skapa/Kopiera NSF till servern

@enduml