@startuml SBE19
'skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
participant CTDkast
box "Töm SBE19" #LightBlue
participant SeatermV2

end box
box "Visa" #GreenYellow
participant GUI1

end box
collections Config
participant SBEproc
database Local
database Scifi01
database Svepa

User -> Svepa: Starta SVEPA CTD-event
User -> CTDkast: Kör SBE19 CTD-kast
User -> SeatermV2: Töm SBE19
SeatermV2 -> Local: En eller flera hex-filer


User -> Config: Valt SBE19
Config -> GUI1: Hämtar SBE19 XMLCON

alt Välj en fil utifrån stationsnummer
    User -> Local: Välj en fil utifrån stationsnummer?
    Svepa -> GUI1: Klicka Svepa: Hämta stationsinfo, pos, stationsnamn etc. 
    else SVEPA info saknas
    User -> GUI1: Ange stationsinfo manuellt
    
end
User -> GUI1: Ange CTD-operatör

GUI1 -> SBEproc: Skapa filnamn, headerinfo
SBEproc -> Scifi01: 

@enduml