@startuml Försystem
'skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
box "Välj CTD: Knappar" #LightBlue
participant CTDs
participant "Sensor_OK"
end box
box "Välj CTD: Visa" #GreenYellow
participant GUI_fält_1
end box
box "Inför/På Station: Fält" #LightGreen
participant Cruise
participant Serie
participant Station
participant Position
participant Depth
participant Distance

end box
box "Inför/På Station: Visa" #GreenYellow
participant GUI_fält_2
end box

box "Inför/På Station: Knappar" #LightBlue
participant Svepa
participant Validate
participant Seasave
end box
collections Config

database stations 
database "Data Scifi01"
database "Data raw"
database "Data local"

database svepa

== Välj CTD och visa sensorinfo, root dirs==
User -> CTDs: Välj CTD
CTDs -> GUI_fält_1: Visa vald CTD
CTDs -> "Config": Hämtar XMLCON info 
Config -> GUI_fält_1: Visa sökväg XMLCON 
Config -> GUI_fält_1: Visa sensornamn o sensorid  
"Data raw" -> GUI_fält_1: \\\scifi01\\scifi\\Data\\mcseabirdchem\\data\\
"Data Scifi01" -> GUI_fält_1: \\\scifi01\\scifi\\Processed\\mcseabirdchem\\data\\ 
"Data local" -> GUI_fält_1: C:\ctd\data\

User -> Sensor_OK: Sensoruppsättning OK
Sensor_OK -> Config: Uppdatera Seasave PSA-fil m XMLCON
Sensor_OK -> Cruise: Gå till Inför Station

== Ange Cruise, Serienr, välj station och operator ==
User -> Cruise: Innevarande år YYYY förvalt. Ange Cruise nummer. Spara till nästa session
Cruise -> GUI_fält_2: Sätt cruisenr
User -> Serie: Ange serienummer. Spara till nästa session + 1 (Uppräkning vid nytt kast)
Serie -> "Data Scifi01": Kolla om serienummret redan finns.
    alt Serien hittades inte
        "Data Scifi01"-> GUI_fält_2: Unik serie, sätt serienr. 
        else Serien finns redan
        "Data Scifi01"-> GUI_fält_2: Felmeddelane. Serien finns redan. Kan ej gå vidare.
    end

alt Välj Station i Listan
    User -> Station : Väljer station från lista 
    Station -> stations : Hämtar information om station 
    stations -> GUI_fält_2 : Sätter nominell pos
    stations -> GUI_fält_2 : Sätter djup
else Skriv in stationsnamn (Extra station/Fiske)
    GUI_fält_2 -> GUI_fält_2 : Stationsnamn (fritext)
    GUI_fält_2 -> GUI_fält_2 : Sätter djup (heltal, 0-1000)
end    

User -> GUI_fält_2: Ange CTD-operatör, ingen kontroll (fritext, 5 tecken)

== Manuell position ==
User -> Position : Skriver in position
Position -> Position : Focus out\n(båda ifyllda)
Position -> stations : Söker efter närmaste station
    alt Station hittades 
        stations -> User : Popup: Bekräfta närmaste station 
        User -> User : Väljer i lista? 
        stations -> Station : Sätter stationsnamn
        stations -> Depth : Sätter djup 
        stations -> Distance : Sätter avstånd till station
    else Station hittades inte 
        stations -> User : Popup: Frågar om ny station\n(visar närmaste station)
        alt Bekräfta ny staion 
            User -> User : "Yes"
            Station -> Station : Sätter till <blank>
            Depth -> Depth : Sätter till <blank>
            Distance -> Distance : Sätter avstånd till närmaste station?
            User -> Station : Anger stationsnamn?
            User -> Depth : Anger djup
        else Inte ny station 
            User -> User : "No"
            Station -> Station : Sätter till <blank>
            Depth -> Depth : Sätter till <blank>
            Distance -> Distance : Sätter till <blank>

        end
    end


== Ladda Svepa  ==
User -> Svepa : Trycker på knapp
Svepa -> svepa : Frågar om information
    alt Svepa är startad
    svepa -> Cruise : Sätter nr och år
    svepa -> Position : Sätter position
    svepa -> stations : Frågar efter närmaste station
        alt Station hittades 
            stations -> Station : Sätter stationsnamn
            stations -> Depth : Sätter djup 
            stations -> Distance : Sätter avstånd till station
        else Station hittades inte
            Station -> Station : Sätter till <blank>
            Depth -> Depth : Sätter till <blank>
            Distance -> Distance : Sätter avstånd till närmaste station?
        end
    else Svepa är inte startad
    svepa -> GUI_fält_2: Ge felmeddelande att Svepa inte är startad. 
    else Ingen kontakt med Svepa
    svepa -> GUI_fält_2: Ge felmeddelande att kontakt m Svepa saknas. Fyll i stationsinfo manuellt. 
    end


== Validera station ==
User -> Validate : Trycker på knapp 
Validate -> GUI_fält_2: Vad skall valideras? Position och djup? Skall validering ske när man klickar SeaSave?

== Starta SeaSave ==
User -> Seasave: Klicka SeaSave
Validate -> GUI_fält_2: Validera inmatade info?
    alt Om info OK uppdatera Seasave PSA-fil och starta Seasave
    GUI_fält_2 -> Config: Sätt År-Fartyg-Cruisenr i seasave PSA-fil
    GUI_fält_2 -> Config: Sätt Serienr i seasave PSA-fil
    GUI_fält_2 -> Config: Sätt Stationsnamn i seasave PSA-fil
    GUI_fält_2 -> Config: Sätt Depth och Y-tick i seasave PSA-fil
    GUI_fält_2 -> Config: Sätt CTD-operatör i seasave PSA-fil
    GUI_fält_2 -> Config: Sätt filnamn (SBE09_1387_20200207_0801_77_SE_01_0120.hex) PSA-fil
    else info ej ok
    Validate -> GUI_fält_2: Ge felmeddelande. Ange vad som behöver justeras. Markera fält
    end

@enduml