@startuml Försystem
'skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
box "Välj CTD: Knappar" #LightBlue
participant CTDs
participant "Sensor_OK"
end box
box "Välj CTD: Visa" #GreenYellow
participant GUI_fält_1
end box
box "Inför/På Station: Fält" #LightGreen
participant Cruise
participant Serie
participant Station
participant Position
participant Depth
participant Distance
end box
box "Inför/På Station: Visa" #GreenYellow
participant GUI_fält_2
end box

box "Inför/På Station: Knappar" #LightBlue
participant Svepa
participant Validate
participant Seasave
end box
collections Config
collections "Config/SBE/XMLCON"
collections "Config/SBE/Sesave_PSA"
database stations 
database "Data Scifi01"
database "Data raw"
database "Data local"

database svepa

== Välj CTD och visa sensorinfo, root dirs==
User -> CTDs: Välj CTD
CTDs -> GUI_fält_1: Visa vald CTD
CTDs -> "Config/SBE/XMLCON": Hämtar XMLCON info 
"Config/SBE/XMLCON" -> GUI_fält_1: Visa sökväg XMLCON 
"Config/SBE/XMLCON" -> GUI_fält_1: Visa sensornamn o sensorid  
Config -> GUI_fält_1: Visa default config dir (c:/ctd/config)
"Data raw" -> GUI_fält_1: \\\scifi01\\scifi\\Data\\mcseabirdchem\\data\\
"Data Scifi01" -> GUI_fält_1: \\\scifi01\\scifi\\Processed\\mcseabirdchem\\data\\ 
"Data local" -> GUI_fält_1: C:\ctd\data\

User -> Sensor_OK: Sensoruppsättning OK
Sensor_OK -> "Config/SBE/Sesave_PSA": Uppdatera Seasave PSA-fil m XMLCON
Sensor_OK -> Cruise:Gå till Inför Station

== Ange Cruise, Serienr, välj station och operator ==
User -> Cruise: Innevarande år YYYY förvalt. Ange Cruise nummer. Spara till nästa session
User -> Serie: Ange serienummer
Serie -> "Data Scifi01": Kolla om serienummret redan finns. 
"Data Scifi01"-> GUI_fält_2: Ge felmeddelande om serienummret redan finns. 
User -> Station : Väljer station från lista 
Station -> stations : Hämtar information om station 
stations -> GUI_fält_2 : Sätter nominell pos
stations -> GUI_fält_2 : Sätter djup


== Manuell position ==
User -> Position : Skriver in position
Position -> Position : Focus out\n(båda ifyllda)
Position -> stations : Söker efter närmaste station
    alt Station hittades 
        stations -> User : Popup: Bekräfta närmaste station 
        User -> User : Väljer i lista? 
        stations -> Station : Sätter stationsnamn
        stations -> Depth : Sätter djup 
        stations -> Distance : Sätter avstånd till station
    else Station hittades inte 
        stations -> User : Popup: Frågar om ny station\n(visar närmaste station)
        alt Bekräfta ny staion 
            User -> User : "Yes"
            Station -> Station : Sätter till <blank>
            Depth -> Depth : Sätter till <blank>
            Distance -> Distance : Sätter avstånd till närmaste station?
            User -> Station : Anger stationsnamn?
            User -> Depth : Anger djup
        else Inte ny station 
            User -> User : "No"
            Station -> Station : Sätter till <blank>
            Depth -> Depth : Sätter till <blank>
            Distance -> Distance : Sätter till <blank>

        end
    end


== Ladda Svepa ==
User -> Svepa : Trycker på knapp
Svepa -> svepa : Frågar om information
svepa -> Cruise : Sätter nr och år
svepa -> Position : Sätter position
svepa -> stations : Frågar efter närmaste station
    alt Station hittades 
        stations -> Station : Sätter stationsnamn
        stations -> Depth : Sätter djup 
        stations -> Distance : Sätter avstånd till station
    else Station hittades inte
        Station -> Station : Sätter till <blank>
        Depth -> Depth : Sätter till <blank>
        Distance -> Distance : Sätter avstånd till närmaste station?
    end



== Validera station ==
User -> Validate : Trycker på knapp 


@enduml